### ISSUE TITLE
wrong Push shown in status

### ISSUE THREAD

**Issue by fommil** [magit/magit-push-remote#5]
I'm sure you're aware of this, it's too obvious :smile: but just incase you aren't... when I add a default pushremote the guide still looks like this:

```
Remote:   master @ upstream (git@ghe:github/foo.git)
Push:     origin @ upstream (git@ghe:github/foo.git)
```

when it should look like

```
Remote:   master @ upstream (git@ghe:github/foo.git)
Push:     blah @ origin (git@ghe:fommil/foo.git)
```

**Comment by tarsius** [comment]
In this case it's harder to figure out what's going on and what should actually happen than with the other issues. I'll have to actually use the package to do so. By the way I cannot really recommend you use this package, I am only keeping it alive because I didn't get around to implement https://github.com/magit/magit/issues/1485 yet.

**Comment by fommil** [comment]
since magit ignores the `remote.pushdefault` setting, it is **extremely** dangerous for me not to use this plugin. Without this plugin, if I were to `P P` then I'd end up pushing to our project's release branch, not my feature branch.

**Comment by fommil** [comment]
a possibly related bug is that the "unpushed commits" list is with respect to the pull remote, not the push remote... I think it should be with respect to the push remote.

**Comment by tarsius** [comment]
I have just made another attempt at getting this to work again. I failed - after I had deleted everything that was not suitable for the current version of Magit anymore, the file was empty. In other words, to fix this I would effectively have to implement a poor version of magit/magit#1485 from scratch. I am not gonna do that. Instead I am deprecating this package and intend to implement proper push remote support fairly soon after I have released `2.1.0` instead.

> since magit ignores the `remote.pushdefault` setting, it is **extremely** dangerous for me not to use this plugin. Without this plugin, if I were to `P P` then I'd end up pushing to our project's release branch, not my feature branch.

I recommend you update to the `next` branch and use `P e` aka "push to elsewhere". To reduce the risk of accidentally pushing to the wrong remote, you could additionally remove the dangerous variant:

``` lisp
(magit-remove-popup-key 'magit-push-popup :actions ?P)
(magit-change-popup-key 'magit-push-popup :actions ?e ?P)
```

**Comment by fommil** [comment]
I guess that's good news, looking forward to it! 
:-D

**Comment by fommil** [comment]
I'm using the latest MELPA snapshot. I don't plan on following any other branches unless you need me to beta test, and I get this using the above snippet you gave me:

``` elisp
Symbol's function definition is void: magit-remove-popup-key
```

**Comment by fommil** [comment]
I can't even find out which package `magit-remove-popup-key` is from. It's not in any of my magit packages.

**Comment by tarsius** [comment]
The Melpa package is still built from the `master` branch. The only way to get the `next` branch is to use Git. Whether you want to do that is up to you. It is ready except for documentation and some polish.

> I can't even find out which package `magit-remove-popup-key` is from. It's not in any of my magit packages.

It's defined in `magit-popup.el` on the `next` branch. It is available as a separate package from Melpa, because it can be used outside of Magit. Unlike the `magit` package on Melpa, the `magit-popup` package is build from Magit's `next` branch. The `magit` package on Melpa, does **not** depend on the `magit-popup` package, but installing both doesn't cause any problems.

**Comment by fommil** [comment]
heh, now it can't find `magit-push-popup`. I think I'll wait for `next` to come on MELPA and just change my workflow so that the remote is `origin` instead of `upstream`
